patrol_node:
  ros__parameters:
    initial_point: [0.0, 0.0, 0.0]
    target_points: [
       8.0, -2.5, 3.14,  # 目标点1：左上病房，朝左
      -3.0, -2.8, 3.14,  # 目标点2：右上病房，朝右
      -7.5,  2.0, 0.0,   # 目标点3：右下病房，朝下
       0.0,  0.0, 0.0    # 目标点4：返回中央大厅，朝上
    ]